<?php
// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `cmd2mccn.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once 'comm.php';

if(!interface_exists('CmdTxRxICE_CmdToMCCN'))
{
    interface CmdTxRxICE_CmdToMCCN
    {
        public function mccnAddSmpAcl($cmd);
        public function mccnAddFullAcl($cmd);
        public function mccnQrySrvTypeRule($cmd);
        public function mccnQrySrvTypeRuleContent($cmd);
        public function mccnQryStatSrvType($cmd);
        public function mccnQryStatRuleType($cmd);
        public function mccnQrySglRltRuleContent($cmd);
        public function mccnQrySglRltRuleCount($cmd);
        public function mccnQryNetRuleContent($cmd);
        public function mccnQryNetRuleCount($cmd);
        public function mccnQryAllRuleContent($cmd);
        public function mccnQryAllRuleCount($cmd);
        public function mccnDelSrvTypeRuleContent($cmd);
        public function mccnDelRuleType($cmd);
        public function mccnDelSglRule($cmd);
        public function mccnDelSglRuleRelated($cmd);
        public function mccnDelNetRule($cmd);
        public function mccnDelAllRule($cmd);
        public function mccnQuit($cmd);
    }

    class CmdTxRxICE_CmdToMCCNPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::CmdTxRxICE::CmdToMCCN', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::CmdTxRxICE::CmdToMCCN', $facet);
        }
    }

    $CmdTxRxICE__t_CmdToMCCN = IcePHP_defineClass('::CmdTxRxICE::CmdToMCCN', 'CmdTxRxICE_CmdToMCCN', true, $Ice__t_Object, null, null);

    $CmdTxRxICE__t_CmdToMCCNPrx = IcePHP_defineProxy($CmdTxRxICE__t_CmdToMCCN);

    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnAddSmpAcl', 0, 0, array($CmdTxRxICE__t_CmdAddSmpAcl), null, $CmdTxRxICE__t_RespAddSmpAcl, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnAddFullAcl', 0, 0, array($CmdTxRxICE__t_CmdAddFullAcl), null, $CmdTxRxICE__t_RespAddFullAcl, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnQrySrvTypeRule', 0, 0, array($CmdTxRxICE__t_CmdQrySrvTypeRule), null, $CmdTxRxICE__t_RespQrySrvTypeRule, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnQrySrvTypeRuleContent', 0, 0, array($CmdTxRxICE__t_CmdQrySrvTypeRuleContent), null, $CmdTxRxICE__t_RespQrySrvTypeRuleContent, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnQryStatSrvType', 0, 0, array($CmdTxRxICE__t_CmdQryStatSrvType), null, $CmdTxRxICE__t_RespQryStatSrvType, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnQryStatRuleType', 0, 0, array($CmdTxRxICE__t_CmdQryStatRuleType), null, $CmdTxRxICE__t_RespQryStatRuleType, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnQrySglRltRuleContent', 0, 0, array($CmdTxRxICE__t_CmdQrySglRltRuleContent), null, $CmdTxRxICE__t_RespQrySglRltRuleContent, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnQrySglRltRuleCount', 0, 0, array($CmdTxRxICE__t_CmdQrySglRltRuleCount), null, $CmdTxRxICE__t_RespQrySglRltRuleCount, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnQryNetRuleContent', 0, 0, array($CmdTxRxICE__t_CmdQryNetRuleContent), null, $CmdTxRxICE__t_RespQryNetRuleContent, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnQryNetRuleCount', 0, 0, array($CmdTxRxICE__t_CmdQryNetRuleCount), null, $CmdTxRxICE__t_RespQryNetRuleCount, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnQryAllRuleContent', 0, 0, array($CmdTxRxICE__t_CmdQryAllRuleContent), null, $CmdTxRxICE__t_RespQryAllRuleContent, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnQryAllRuleCount', 0, 0, array($CmdTxRxICE__t_CmdQryAllRuleCount), null, $CmdTxRxICE__t_RespQryAllRuleCount, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnDelSrvTypeRuleContent', 0, 0, array($CmdTxRxICE__t_CmdDelSrvTypeRuleContent), null, $CmdTxRxICE__t_RespDelSrvTypeRuleContent, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnDelRuleType', 0, 0, array($CmdTxRxICE__t_CmdDelRuleType), null, $CmdTxRxICE__t_RespDelRuleType, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnDelSglRule', 0, 0, array($CmdTxRxICE__t_CmdDelSglRule), null, $CmdTxRxICE__t_RespDelSglRule, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnDelSglRuleRelated', 0, 0, array($CmdTxRxICE__t_CmdDelSglRuleRelated), null, $CmdTxRxICE__t_RespDelSglRuleRelated, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnDelNetRule', 0, 0, array($CmdTxRxICE__t_CmdDelNetRule), null, $CmdTxRxICE__t_RespDelNetRule, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnDelAllRule', 0, 0, array($CmdTxRxICE__t_CmdDelAllRule), null, $CmdTxRxICE__t_RespDelAllRule, null);
    IcePHP_defineOperation($CmdTxRxICE__t_CmdToMCCN, 'mccnQuit', 0, 0, array($CmdTxRxICE__t_CmdQuit), null, $CmdTxRxICE__t_RespQuit, null);
}
?>
