<?php
// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `comm.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


if(!class_exists('CmdTxRxICE_UsrInfo'))
{
    class CmdTxRxICE_UsrInfo
    {
        public function __construct($name='', $pwd='')
        {
            $this->name = $name;
            $this->pwd = $pwd;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_UsrInfo;
            return IcePHP_stringify($this, $CmdTxRxICE__t_UsrInfo);
        }

        public $name;
        public $pwd;
    }

    $CmdTxRxICE__t_UsrInfo = IcePHP_defineStruct('::CmdTxRxICE::UsrInfo', 'CmdTxRxICE_UsrInfo', array(
        array('name', $IcePHP__t_string), 
        array('pwd', $IcePHP__t_string)));
}

if(!class_exists('CmdTxRxICE_Dpi'))
{
    class CmdTxRxICE_Dpi
    {
        public function __construct($ip=0, $port=0, $id='')
        {
            $this->ip = $ip;
            $this->port = $port;
            $this->id = $id;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_Dpi;
            return IcePHP_stringify($this, $CmdTxRxICE__t_Dpi);
        }

        public $ip;
        public $port;
        public $id;
    }

    $CmdTxRxICE__t_Dpi = IcePHP_defineStruct('::CmdTxRxICE::Dpi', 'CmdTxRxICE_Dpi', array(
        array('ip', $IcePHP__t_int), 
        array('port', $IcePHP__t_short), 
        array('id', $IcePHP__t_string)));
}

if(!isset($CmdTxRxICE__t_DPIVector))
{
    $CmdTxRxICE__t_DPIVector = IcePHP_defineSequence('::CmdTxRxICE::DPIVector', $CmdTxRxICE__t_Dpi);
}

if(!class_exists('CmdTxRxICE_CmdPubInfo'))
{
    class CmdTxRxICE_CmdPubInfo
    {
        public function __construct($usr=null, $srvId=0, $dpiList=null)
        {
            $this->usr = is_null($usr) ? new CmdTxRxICE_UsrInfo : $usr;
            $this->srvId = $srvId;
            $this->dpiList = $dpiList;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdPubInfo;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdPubInfo);
        }

        public $usr;
        public $srvId;
        public $dpiList;
    }

    $CmdTxRxICE__t_CmdPubInfo = IcePHP_defineStruct('::CmdTxRxICE::CmdPubInfo', 'CmdTxRxICE_CmdPubInfo', array(
        array('usr', $CmdTxRxICE__t_UsrInfo), 
        array('srvId', $IcePHP__t_byte), 
        array('dpiList', $CmdTxRxICE__t_DPIVector)));
}

if(!class_exists('CmdTxRxICE_RespPubInfo'))
{
    class CmdTxRxICE_RespPubInfo
    {
        public function __construct($exCode=0)
        {
            $this->exCode = $exCode;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespPubInfo;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespPubInfo);
        }

        public $exCode;
    }

    $CmdTxRxICE__t_RespPubInfo = IcePHP_defineStruct('::CmdTxRxICE::RespPubInfo', 'CmdTxRxICE_RespPubInfo', array(
        array('exCode', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_SmpAclInfo'))
{
    class CmdTxRxICE_SmpAclInfo
    {
        public function __construct($ruleDirection=0, $srcIP=0, $dstIP=0, $srcPort=0, $dstPort=0, $protocalId=0)
        {
            $this->ruleDirection = $ruleDirection;
            $this->srcIP = $srcIP;
            $this->dstIP = $dstIP;
            $this->srcPort = $srcPort;
            $this->dstPort = $dstPort;
            $this->protocalId = $protocalId;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_SmpAclInfo;
            return IcePHP_stringify($this, $CmdTxRxICE__t_SmpAclInfo);
        }

        public $ruleDirection;
        public $srcIP;
        public $dstIP;
        public $srcPort;
        public $dstPort;
        public $protocalId;
    }

    $CmdTxRxICE__t_SmpAclInfo = IcePHP_defineStruct('::CmdTxRxICE::SmpAclInfo', 'CmdTxRxICE_SmpAclInfo', array(
        array('ruleDirection', $IcePHP__t_byte), 
        array('srcIP', $IcePHP__t_int), 
        array('dstIP', $IcePHP__t_int), 
        array('srcPort', $IcePHP__t_short), 
        array('dstPort', $IcePHP__t_short), 
        array('protocalId', $IcePHP__t_byte)));
}

if(!class_exists('CmdTxRxICE_FullAclInfo'))
{
    class CmdTxRxICE_FullAclInfo
    {
        public function __construct($ruleDirection=0, $srvId=0, $srcIP=0, $dstIP=0, $srcPort=0, $dstPort=0, $protocalId=0, $srcIPMask=0, $dstIPMask=0, $srcPortMask=0, $dstPortMask=0, $protocalIdMask=0)
        {
            $this->ruleDirection = $ruleDirection;
            $this->srvId = $srvId;
            $this->srcIP = $srcIP;
            $this->dstIP = $dstIP;
            $this->srcPort = $srcPort;
            $this->dstPort = $dstPort;
            $this->protocalId = $protocalId;
            $this->srcIPMask = $srcIPMask;
            $this->dstIPMask = $dstIPMask;
            $this->srcPortMask = $srcPortMask;
            $this->dstPortMask = $dstPortMask;
            $this->protocalIdMask = $protocalIdMask;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_FullAclInfo;
            return IcePHP_stringify($this, $CmdTxRxICE__t_FullAclInfo);
        }

        public $ruleDirection;
        public $srvId;
        public $srcIP;
        public $dstIP;
        public $srcPort;
        public $dstPort;
        public $protocalId;
        public $srcIPMask;
        public $dstIPMask;
        public $srcPortMask;
        public $dstPortMask;
        public $protocalIdMask;
    }

    $CmdTxRxICE__t_FullAclInfo = IcePHP_defineStruct('::CmdTxRxICE::FullAclInfo', 'CmdTxRxICE_FullAclInfo', array(
        array('ruleDirection', $IcePHP__t_byte), 
        array('srvId', $IcePHP__t_byte), 
        array('srcIP', $IcePHP__t_int), 
        array('dstIP', $IcePHP__t_int), 
        array('srcPort', $IcePHP__t_short), 
        array('dstPort', $IcePHP__t_short), 
        array('protocalId', $IcePHP__t_short), 
        array('srcIPMask', $IcePHP__t_int), 
        array('dstIPMask', $IcePHP__t_int), 
        array('srcPortMask', $IcePHP__t_short), 
        array('dstPortMask', $IcePHP__t_short), 
        array('protocalIdMask', $IcePHP__t_short)));
}

if(!class_exists('CmdTxRxICE_FeedbkMb'))
{
    class CmdTxRxICE_FeedbkMb
    {
        public function __construct($acl=null, $ruleId=0, $hitCount=0, $recvTime=0, $cltIp=0, $usrName=0)
        {
            $this->acl = is_null($acl) ? new CmdTxRxICE_FullAclInfo : $acl;
            $this->ruleId = $ruleId;
            $this->hitCount = $hitCount;
            $this->recvTime = $recvTime;
            $this->cltIp = $cltIp;
            $this->usrName = $usrName;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_FeedbkMb;
            return IcePHP_stringify($this, $CmdTxRxICE__t_FeedbkMb);
        }

        public $acl;
        public $ruleId;
        public $hitCount;
        public $recvTime;
        public $cltIp;
        public $usrName;
    }

    $CmdTxRxICE__t_FeedbkMb = IcePHP_defineStruct('::CmdTxRxICE::FeedbkMb', 'CmdTxRxICE_FeedbkMb', array(
        array('acl', $CmdTxRxICE__t_FullAclInfo), 
        array('ruleId', $IcePHP__t_int), 
        array('hitCount', $IcePHP__t_int), 
        array('recvTime', $IcePHP__t_int), 
        array('cltIp', $IcePHP__t_int), 
        array('usrName', $IcePHP__t_int)));
}

if(!isset($CmdTxRxICE__t_FeedbkVector))
{
    $CmdTxRxICE__t_FeedbkVector = IcePHP_defineSequence('::CmdTxRxICE::FeedbkVector', $CmdTxRxICE__t_FeedbkMb);
}

if(!class_exists('CmdTxRxICE_NetInfo'))
{
    class CmdTxRxICE_NetInfo
    {
        public function __construct($type=0, $srcIpBgn=0, $srcIpEnd=0, $dstIpBgn=0, $dstIpEnd=0)
        {
            $this->type = $type;
            $this->srcIpBgn = $srcIpBgn;
            $this->srcIpEnd = $srcIpEnd;
            $this->dstIpBgn = $dstIpBgn;
            $this->dstIpEnd = $dstIpEnd;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_NetInfo;
            return IcePHP_stringify($this, $CmdTxRxICE__t_NetInfo);
        }

        public $type;
        public $srcIpBgn;
        public $srcIpEnd;
        public $dstIpBgn;
        public $dstIpEnd;
    }

    $CmdTxRxICE__t_NetInfo = IcePHP_defineStruct('::CmdTxRxICE::NetInfo', 'CmdTxRxICE_NetInfo', array(
        array('type', $IcePHP__t_short), 
        array('srcIpBgn', $IcePHP__t_int), 
        array('srcIpEnd', $IcePHP__t_int), 
        array('dstIpBgn', $IcePHP__t_int), 
        array('dstIpEnd', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_CmdAddSmpAcl'))
{
    class CmdTxRxICE_CmdAddSmpAcl
    {
        public function __construct($pubInfo=null, $acl=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
            $this->acl = is_null($acl) ? new CmdTxRxICE_SmpAclInfo : $acl;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdAddSmpAcl;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdAddSmpAcl);
        }

        public $pubInfo;
        public $acl;
    }

    $CmdTxRxICE__t_CmdAddSmpAcl = IcePHP_defineStruct('::CmdTxRxICE::CmdAddSmpAcl', 'CmdTxRxICE_CmdAddSmpAcl', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo), 
        array('acl', $CmdTxRxICE__t_SmpAclInfo)));
}

if(!class_exists('CmdTxRxICE_RespAddSmpAcl'))
{
    class CmdTxRxICE_RespAddSmpAcl
    {
        public function __construct($exInfo=null, $rstCode=0)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->rstCode = $rstCode;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespAddSmpAcl;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespAddSmpAcl);
        }

        public $exInfo;
        public $rstCode;
    }

    $CmdTxRxICE__t_RespAddSmpAcl = IcePHP_defineStruct('::CmdTxRxICE::RespAddSmpAcl', 'CmdTxRxICE_RespAddSmpAcl', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('rstCode', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_CmdAddFullAcl'))
{
    class CmdTxRxICE_CmdAddFullAcl
    {
        public function __construct($pubInfo=null, $acl=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
            $this->acl = is_null($acl) ? new CmdTxRxICE_FullAclInfo : $acl;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdAddFullAcl;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdAddFullAcl);
        }

        public $pubInfo;
        public $acl;
    }

    $CmdTxRxICE__t_CmdAddFullAcl = IcePHP_defineStruct('::CmdTxRxICE::CmdAddFullAcl', 'CmdTxRxICE_CmdAddFullAcl', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo), 
        array('acl', $CmdTxRxICE__t_FullAclInfo)));
}

if(!class_exists('CmdTxRxICE_RespAddFullAcl'))
{
    class CmdTxRxICE_RespAddFullAcl
    {
        public function __construct($exInfo=null, $rstCode=0)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->rstCode = $rstCode;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespAddFullAcl;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespAddFullAcl);
        }

        public $exInfo;
        public $rstCode;
    }

    $CmdTxRxICE__t_RespAddFullAcl = IcePHP_defineStruct('::CmdTxRxICE::RespAddFullAcl', 'CmdTxRxICE_RespAddFullAcl', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('rstCode', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_CmdQrySrvTypeRule'))
{
    class CmdTxRxICE_CmdQrySrvTypeRule
    {
        public function __construct($pubInfo=null, $srvId=0)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
            $this->srvId = $srvId;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdQrySrvTypeRule;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdQrySrvTypeRule);
        }

        public $pubInfo;
        public $srvId;
    }

    $CmdTxRxICE__t_CmdQrySrvTypeRule = IcePHP_defineStruct('::CmdTxRxICE::CmdQrySrvTypeRule', 'CmdTxRxICE_CmdQrySrvTypeRule', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo), 
        array('srvId', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_RespQrySrvTypeRule'))
{
    class CmdTxRxICE_RespQrySrvTypeRule
    {
        public function __construct($exInfo=null, $ruleCount=0, $hitCount=0)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->ruleCount = $ruleCount;
            $this->hitCount = $hitCount;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespQrySrvTypeRule;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespQrySrvTypeRule);
        }

        public $exInfo;
        public $ruleCount;
        public $hitCount;
    }

    $CmdTxRxICE__t_RespQrySrvTypeRule = IcePHP_defineStruct('::CmdTxRxICE::RespQrySrvTypeRule', 'CmdTxRxICE_RespQrySrvTypeRule', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('ruleCount', $IcePHP__t_int), 
        array('hitCount', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_CmdQrySrvTypeRuleContent'))
{
    class CmdTxRxICE_CmdQrySrvTypeRuleContent
    {
        public function __construct($pubInfo=null, $srvId=0)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
            $this->srvId = $srvId;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdQrySrvTypeRuleContent;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdQrySrvTypeRuleContent);
        }

        public $pubInfo;
        public $srvId;
    }

    $CmdTxRxICE__t_CmdQrySrvTypeRuleContent = IcePHP_defineStruct('::CmdTxRxICE::CmdQrySrvTypeRuleContent', 'CmdTxRxICE_CmdQrySrvTypeRuleContent', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo), 
        array('srvId', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_RespQrySrvTypeRuleContent'))
{
    class CmdTxRxICE_RespQrySrvTypeRuleContent
    {
        public function __construct($exInfo=null, $mbVct=null)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->mbVct = $mbVct;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespQrySrvTypeRuleContent;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespQrySrvTypeRuleContent);
        }

        public $exInfo;
        public $mbVct;
    }

    $CmdTxRxICE__t_RespQrySrvTypeRuleContent = IcePHP_defineStruct('::CmdTxRxICE::RespQrySrvTypeRuleContent', 'CmdTxRxICE_RespQrySrvTypeRuleContent', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('mbVct', $CmdTxRxICE__t_FeedbkVector)));
}

if(!class_exists('CmdTxRxICE_CmdQryStatSrvType'))
{
    class CmdTxRxICE_CmdQryStatSrvType
    {
        public function __construct($pubInfo=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdQryStatSrvType;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdQryStatSrvType);
        }

        public $pubInfo;
    }

    $CmdTxRxICE__t_CmdQryStatSrvType = IcePHP_defineStruct('::CmdTxRxICE::CmdQryStatSrvType', 'CmdTxRxICE_CmdQryStatSrvType', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo)));
}

if(!class_exists('CmdTxRxICE_SrvTypeInfo'))
{
    class CmdTxRxICE_SrvTypeInfo
    {
        public function __construct($type=0, $thisRuleCount=0, $thisHitCount=0)
        {
            $this->type = $type;
            $this->thisRuleCount = $thisRuleCount;
            $this->thisHitCount = $thisHitCount;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_SrvTypeInfo;
            return IcePHP_stringify($this, $CmdTxRxICE__t_SrvTypeInfo);
        }

        public $type;
        public $thisRuleCount;
        public $thisHitCount;
    }

    $CmdTxRxICE__t_SrvTypeInfo = IcePHP_defineStruct('::CmdTxRxICE::SrvTypeInfo', 'CmdTxRxICE_SrvTypeInfo', array(
        array('type', $IcePHP__t_short), 
        array('thisRuleCount', $IcePHP__t_int), 
        array('thisHitCount', $IcePHP__t_int)));
}

if(!isset($CmdTxRxICE__t_SrvTypeInfoVector))
{
    $CmdTxRxICE__t_SrvTypeInfoVector = IcePHP_defineSequence('::CmdTxRxICE::SrvTypeInfoVector', $CmdTxRxICE__t_SrvTypeInfo);
}

if(!class_exists('CmdTxRxICE_RespQryStatSrvType'))
{
    class CmdTxRxICE_RespQryStatSrvType
    {
        public function __construct($exInfo=null, $ruleCount=0, $denyCount=0, $redirectCount=0, $inUseSrvTypeCount=0, $typeInfoVct=null)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->ruleCount = $ruleCount;
            $this->denyCount = $denyCount;
            $this->redirectCount = $redirectCount;
            $this->inUseSrvTypeCount = $inUseSrvTypeCount;
            $this->typeInfoVct = $typeInfoVct;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespQryStatSrvType;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespQryStatSrvType);
        }

        public $exInfo;
        public $ruleCount;
        public $denyCount;
        public $redirectCount;
        public $inUseSrvTypeCount;
        public $typeInfoVct;
    }

    $CmdTxRxICE__t_RespQryStatSrvType = IcePHP_defineStruct('::CmdTxRxICE::RespQryStatSrvType', 'CmdTxRxICE_RespQryStatSrvType', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('ruleCount', $IcePHP__t_int), 
        array('denyCount', $IcePHP__t_int), 
        array('redirectCount', $IcePHP__t_int), 
        array('inUseSrvTypeCount', $IcePHP__t_int), 
        array('typeInfoVct', $CmdTxRxICE__t_SrvTypeInfoVector)));
}

if(!class_exists('CmdTxRxICE_RuleTypeInfo'))
{
    class CmdTxRxICE_RuleTypeInfo
    {
        public function __construct($type=0, $thisRuleCount=0, $thisHitCount=0)
        {
            $this->type = $type;
            $this->thisRuleCount = $thisRuleCount;
            $this->thisHitCount = $thisHitCount;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RuleTypeInfo;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RuleTypeInfo);
        }

        public $type;
        public $thisRuleCount;
        public $thisHitCount;
    }

    $CmdTxRxICE__t_RuleTypeInfo = IcePHP_defineStruct('::CmdTxRxICE::RuleTypeInfo', 'CmdTxRxICE_RuleTypeInfo', array(
        array('type', $IcePHP__t_short), 
        array('thisRuleCount', $IcePHP__t_int), 
        array('thisHitCount', $IcePHP__t_int)));
}

if(!isset($CmdTxRxICE__t_RuleTypeInfoVector))
{
    $CmdTxRxICE__t_RuleTypeInfoVector = IcePHP_defineSequence('::CmdTxRxICE::RuleTypeInfoVector', $CmdTxRxICE__t_RuleTypeInfo);
}

if(!class_exists('CmdTxRxICE_CmdQryStatRuleType'))
{
    class CmdTxRxICE_CmdQryStatRuleType
    {
        public function __construct($pubInfo=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdQryStatRuleType;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdQryStatRuleType);
        }

        public $pubInfo;
    }

    $CmdTxRxICE__t_CmdQryStatRuleType = IcePHP_defineStruct('::CmdTxRxICE::CmdQryStatRuleType', 'CmdTxRxICE_CmdQryStatRuleType', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo)));
}

if(!class_exists('CmdTxRxICE_RespQryStatRuleType'))
{
    class CmdTxRxICE_RespQryStatRuleType
    {
        public function __construct($exInfo=null, $ruleCount=0, $denyCount=0, $redirectCount=0, $inUseRuleTypeCount=0, $typeInfoVct=null)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->ruleCount = $ruleCount;
            $this->denyCount = $denyCount;
            $this->redirectCount = $redirectCount;
            $this->inUseRuleTypeCount = $inUseRuleTypeCount;
            $this->typeInfoVct = $typeInfoVct;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespQryStatRuleType;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespQryStatRuleType);
        }

        public $exInfo;
        public $ruleCount;
        public $denyCount;
        public $redirectCount;
        public $inUseRuleTypeCount;
        public $typeInfoVct;
    }

    $CmdTxRxICE__t_RespQryStatRuleType = IcePHP_defineStruct('::CmdTxRxICE::RespQryStatRuleType', 'CmdTxRxICE_RespQryStatRuleType', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('ruleCount', $IcePHP__t_int), 
        array('denyCount', $IcePHP__t_int), 
        array('redirectCount', $IcePHP__t_int), 
        array('inUseRuleTypeCount', $IcePHP__t_int), 
        array('typeInfoVct', $CmdTxRxICE__t_RuleTypeInfoVector)));
}

if(!class_exists('CmdTxRxICE_CmdQrySglRltRuleContent'))
{
    class CmdTxRxICE_CmdQrySglRltRuleContent
    {
        public function __construct($pubInfo=null, $acl=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
            $this->acl = is_null($acl) ? new CmdTxRxICE_FullAclInfo : $acl;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdQrySglRltRuleContent;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdQrySglRltRuleContent);
        }

        public $pubInfo;
        public $acl;
    }

    $CmdTxRxICE__t_CmdQrySglRltRuleContent = IcePHP_defineStruct('::CmdTxRxICE::CmdQrySglRltRuleContent', 'CmdTxRxICE_CmdQrySglRltRuleContent', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo), 
        array('acl', $CmdTxRxICE__t_FullAclInfo)));
}

if(!class_exists('CmdTxRxICE_RespQrySglRltRuleContent'))
{
    class CmdTxRxICE_RespQrySglRltRuleContent
    {
        public function __construct($exInfo=null, $mbVct=null)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->mbVct = $mbVct;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespQrySglRltRuleContent;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespQrySglRltRuleContent);
        }

        public $exInfo;
        public $mbVct;
    }

    $CmdTxRxICE__t_RespQrySglRltRuleContent = IcePHP_defineStruct('::CmdTxRxICE::RespQrySglRltRuleContent', 'CmdTxRxICE_RespQrySglRltRuleContent', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('mbVct', $CmdTxRxICE__t_FeedbkVector)));
}

if(!class_exists('CmdTxRxICE_CmdQrySglRltRuleCount'))
{
    class CmdTxRxICE_CmdQrySglRltRuleCount
    {
        public function __construct($pubInfo=null, $acl=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
            $this->acl = is_null($acl) ? new CmdTxRxICE_FullAclInfo : $acl;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdQrySglRltRuleCount;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdQrySglRltRuleCount);
        }

        public $pubInfo;
        public $acl;
    }

    $CmdTxRxICE__t_CmdQrySglRltRuleCount = IcePHP_defineStruct('::CmdTxRxICE::CmdQrySglRltRuleCount', 'CmdTxRxICE_CmdQrySglRltRuleCount', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo), 
        array('acl', $CmdTxRxICE__t_FullAclInfo)));
}

if(!class_exists('CmdTxRxICE_RespQrySglRltRuleCount'))
{
    class CmdTxRxICE_RespQrySglRltRuleCount
    {
        public function __construct($exInfo=null, $a=0)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->a = $a;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespQrySglRltRuleCount;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespQrySglRltRuleCount);
        }

        public $exInfo;
        public $a;
    }

    $CmdTxRxICE__t_RespQrySglRltRuleCount = IcePHP_defineStruct('::CmdTxRxICE::RespQrySglRltRuleCount', 'CmdTxRxICE_RespQrySglRltRuleCount', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('a', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_CmdQryNetRuleCount'))
{
    class CmdTxRxICE_CmdQryNetRuleCount
    {
        public function __construct($pubInfo=null, $net=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
            $this->net = is_null($net) ? new CmdTxRxICE_NetInfo : $net;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdQryNetRuleCount;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdQryNetRuleCount);
        }

        public $pubInfo;
        public $net;
    }

    $CmdTxRxICE__t_CmdQryNetRuleCount = IcePHP_defineStruct('::CmdTxRxICE::CmdQryNetRuleCount', 'CmdTxRxICE_CmdQryNetRuleCount', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo), 
        array('net', $CmdTxRxICE__t_NetInfo)));
}

if(!class_exists('CmdTxRxICE_RespQryNetRuleCount'))
{
    class CmdTxRxICE_RespQryNetRuleCount
    {
        public function __construct($exInfo=null, $ruleCount=0)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->ruleCount = $ruleCount;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespQryNetRuleCount;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespQryNetRuleCount);
        }

        public $exInfo;
        public $ruleCount;
    }

    $CmdTxRxICE__t_RespQryNetRuleCount = IcePHP_defineStruct('::CmdTxRxICE::RespQryNetRuleCount', 'CmdTxRxICE_RespQryNetRuleCount', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('ruleCount', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_CmdQryNetRuleContent'))
{
    class CmdTxRxICE_CmdQryNetRuleContent
    {
        public function __construct($pubInfo=null, $net=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
            $this->net = is_null($net) ? new CmdTxRxICE_NetInfo : $net;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdQryNetRuleContent;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdQryNetRuleContent);
        }

        public $pubInfo;
        public $net;
    }

    $CmdTxRxICE__t_CmdQryNetRuleContent = IcePHP_defineStruct('::CmdTxRxICE::CmdQryNetRuleContent', 'CmdTxRxICE_CmdQryNetRuleContent', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo), 
        array('net', $CmdTxRxICE__t_NetInfo)));
}

if(!class_exists('CmdTxRxICE_RespQryNetRuleContent'))
{
    class CmdTxRxICE_RespQryNetRuleContent
    {
        public function __construct($exInfo=null, $mbVct=null)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->mbVct = $mbVct;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespQryNetRuleContent;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespQryNetRuleContent);
        }

        public $exInfo;
        public $mbVct;
    }

    $CmdTxRxICE__t_RespQryNetRuleContent = IcePHP_defineStruct('::CmdTxRxICE::RespQryNetRuleContent', 'CmdTxRxICE_RespQryNetRuleContent', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('mbVct', $CmdTxRxICE__t_FeedbkVector)));
}

if(!class_exists('CmdTxRxICE_CmdQryAllRuleCount'))
{
    class CmdTxRxICE_CmdQryAllRuleCount
    {
        public function __construct($pubInfo=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdQryAllRuleCount;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdQryAllRuleCount);
        }

        public $pubInfo;
    }

    $CmdTxRxICE__t_CmdQryAllRuleCount = IcePHP_defineStruct('::CmdTxRxICE::CmdQryAllRuleCount', 'CmdTxRxICE_CmdQryAllRuleCount', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo)));
}

if(!class_exists('CmdTxRxICE_RespQryAllRuleCount'))
{
    class CmdTxRxICE_RespQryAllRuleCount
    {
        public function __construct($exInfo=null, $ruleCount=0)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->ruleCount = $ruleCount;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespQryAllRuleCount;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespQryAllRuleCount);
        }

        public $exInfo;
        public $ruleCount;
    }

    $CmdTxRxICE__t_RespQryAllRuleCount = IcePHP_defineStruct('::CmdTxRxICE::RespQryAllRuleCount', 'CmdTxRxICE_RespQryAllRuleCount', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('ruleCount', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_CmdQryAllRuleContent'))
{
    class CmdTxRxICE_CmdQryAllRuleContent
    {
        public function __construct($pubInfo=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdQryAllRuleContent;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdQryAllRuleContent);
        }

        public $pubInfo;
    }

    $CmdTxRxICE__t_CmdQryAllRuleContent = IcePHP_defineStruct('::CmdTxRxICE::CmdQryAllRuleContent', 'CmdTxRxICE_CmdQryAllRuleContent', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo)));
}

if(!class_exists('CmdTxRxICE_RespQryAllRuleContent'))
{
    class CmdTxRxICE_RespQryAllRuleContent
    {
        public function __construct($exInfo=null, $mbVct=null)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->mbVct = $mbVct;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespQryAllRuleContent;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespQryAllRuleContent);
        }

        public $exInfo;
        public $mbVct;
    }

    $CmdTxRxICE__t_RespQryAllRuleContent = IcePHP_defineStruct('::CmdTxRxICE::RespQryAllRuleContent', 'CmdTxRxICE_RespQryAllRuleContent', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('mbVct', $CmdTxRxICE__t_FeedbkVector)));
}

if(!class_exists('CmdTxRxICE_CmdDelSrvTypeRuleContent'))
{
    class CmdTxRxICE_CmdDelSrvTypeRuleContent
    {
        public function __construct($pubInfo=null, $srvId=0)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
            $this->srvId = $srvId;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdDelSrvTypeRuleContent;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdDelSrvTypeRuleContent);
        }

        public $pubInfo;
        public $srvId;
    }

    $CmdTxRxICE__t_CmdDelSrvTypeRuleContent = IcePHP_defineStruct('::CmdTxRxICE::CmdDelSrvTypeRuleContent', 'CmdTxRxICE_CmdDelSrvTypeRuleContent', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo), 
        array('srvId', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_RespDelSrvTypeRuleContent'))
{
    class CmdTxRxICE_RespDelSrvTypeRuleContent
    {
        public function __construct($exInfo=null, $ruleCount=0)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->ruleCount = $ruleCount;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespDelSrvTypeRuleContent;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespDelSrvTypeRuleContent);
        }

        public $exInfo;
        public $ruleCount;
    }

    $CmdTxRxICE__t_RespDelSrvTypeRuleContent = IcePHP_defineStruct('::CmdTxRxICE::RespDelSrvTypeRuleContent', 'CmdTxRxICE_RespDelSrvTypeRuleContent', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('ruleCount', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_CmdDelRuleType'))
{
    class CmdTxRxICE_CmdDelRuleType
    {
        public function __construct($pubInfo=null, $ruleType=0)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
            $this->ruleType = $ruleType;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdDelRuleType;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdDelRuleType);
        }

        public $pubInfo;
        public $ruleType;
    }

    $CmdTxRxICE__t_CmdDelRuleType = IcePHP_defineStruct('::CmdTxRxICE::CmdDelRuleType', 'CmdTxRxICE_CmdDelRuleType', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo), 
        array('ruleType', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_RespDelRuleType'))
{
    class CmdTxRxICE_RespDelRuleType
    {
        public function __construct($exInfo=null, $ruleCount=0)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->ruleCount = $ruleCount;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespDelRuleType;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespDelRuleType);
        }

        public $exInfo;
        public $ruleCount;
    }

    $CmdTxRxICE__t_RespDelRuleType = IcePHP_defineStruct('::CmdTxRxICE::RespDelRuleType', 'CmdTxRxICE_RespDelRuleType', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('ruleCount', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_CmdDelSglRule'))
{
    class CmdTxRxICE_CmdDelSglRule
    {
        public function __construct($pubInfo=null, $acl=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
            $this->acl = is_null($acl) ? new CmdTxRxICE_FullAclInfo : $acl;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdDelSglRule;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdDelSglRule);
        }

        public $pubInfo;
        public $acl;
    }

    $CmdTxRxICE__t_CmdDelSglRule = IcePHP_defineStruct('::CmdTxRxICE::CmdDelSglRule', 'CmdTxRxICE_CmdDelSglRule', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo), 
        array('acl', $CmdTxRxICE__t_FullAclInfo)));
}

if(!class_exists('CmdTxRxICE_RespDelSglRule'))
{
    class CmdTxRxICE_RespDelSglRule
    {
        public function __construct($exInfo=null, $ruleCount=0)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->ruleCount = $ruleCount;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespDelSglRule;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespDelSglRule);
        }

        public $exInfo;
        public $ruleCount;
    }

    $CmdTxRxICE__t_RespDelSglRule = IcePHP_defineStruct('::CmdTxRxICE::RespDelSglRule', 'CmdTxRxICE_RespDelSglRule', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('ruleCount', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_CmdDelSglRuleRelated'))
{
    class CmdTxRxICE_CmdDelSglRuleRelated
    {
        public function __construct($pubInfo=null, $acl=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
            $this->acl = is_null($acl) ? new CmdTxRxICE_FullAclInfo : $acl;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdDelSglRuleRelated;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdDelSglRuleRelated);
        }

        public $pubInfo;
        public $acl;
    }

    $CmdTxRxICE__t_CmdDelSglRuleRelated = IcePHP_defineStruct('::CmdTxRxICE::CmdDelSglRuleRelated', 'CmdTxRxICE_CmdDelSglRuleRelated', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo), 
        array('acl', $CmdTxRxICE__t_FullAclInfo)));
}

if(!class_exists('CmdTxRxICE_RespDelSglRuleRelated'))
{
    class CmdTxRxICE_RespDelSglRuleRelated
    {
        public function __construct($exInfo=null, $ruleCount=0)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->ruleCount = $ruleCount;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespDelSglRuleRelated;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespDelSglRuleRelated);
        }

        public $exInfo;
        public $ruleCount;
    }

    $CmdTxRxICE__t_RespDelSglRuleRelated = IcePHP_defineStruct('::CmdTxRxICE::RespDelSglRuleRelated', 'CmdTxRxICE_RespDelSglRuleRelated', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('ruleCount', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_CmdDelNetRule'))
{
    class CmdTxRxICE_CmdDelNetRule
    {
        public function __construct($pubInfo=null, $net=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
            $this->net = is_null($net) ? new CmdTxRxICE_NetInfo : $net;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdDelNetRule;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdDelNetRule);
        }

        public $pubInfo;
        public $net;
    }

    $CmdTxRxICE__t_CmdDelNetRule = IcePHP_defineStruct('::CmdTxRxICE::CmdDelNetRule', 'CmdTxRxICE_CmdDelNetRule', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo), 
        array('net', $CmdTxRxICE__t_NetInfo)));
}

if(!class_exists('CmdTxRxICE_RespDelNetRule'))
{
    class CmdTxRxICE_RespDelNetRule
    {
        public function __construct($exInfo=null, $ruleCount=0)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->ruleCount = $ruleCount;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespDelNetRule;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespDelNetRule);
        }

        public $exInfo;
        public $ruleCount;
    }

    $CmdTxRxICE__t_RespDelNetRule = IcePHP_defineStruct('::CmdTxRxICE::RespDelNetRule', 'CmdTxRxICE_RespDelNetRule', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('ruleCount', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_CmdDelAllRule'))
{
    class CmdTxRxICE_CmdDelAllRule
    {
        public function __construct($pubInfo=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdDelAllRule;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdDelAllRule);
        }

        public $pubInfo;
    }

    $CmdTxRxICE__t_CmdDelAllRule = IcePHP_defineStruct('::CmdTxRxICE::CmdDelAllRule', 'CmdTxRxICE_CmdDelAllRule', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo)));
}

if(!class_exists('CmdTxRxICE_RespDelAllRule'))
{
    class CmdTxRxICE_RespDelAllRule
    {
        public function __construct($exInfo=null, $ruleCount=0)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->ruleCount = $ruleCount;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespDelAllRule;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespDelAllRule);
        }

        public $exInfo;
        public $ruleCount;
    }

    $CmdTxRxICE__t_RespDelAllRule = IcePHP_defineStruct('::CmdTxRxICE::RespDelAllRule', 'CmdTxRxICE_RespDelAllRule', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('ruleCount', $IcePHP__t_int)));
}

if(!class_exists('CmdTxRxICE_CmdQuit'))
{
    class CmdTxRxICE_CmdQuit
    {
        public function __construct($pubInfo=null)
        {
            $this->pubInfo = is_null($pubInfo) ? new CmdTxRxICE_CmdPubInfo : $pubInfo;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_CmdQuit;
            return IcePHP_stringify($this, $CmdTxRxICE__t_CmdQuit);
        }

        public $pubInfo;
    }

    $CmdTxRxICE__t_CmdQuit = IcePHP_defineStruct('::CmdTxRxICE::CmdQuit', 'CmdTxRxICE_CmdQuit', array(
        array('pubInfo', $CmdTxRxICE__t_CmdPubInfo)));
}

if(!class_exists('CmdTxRxICE_RespQuit'))
{
    class CmdTxRxICE_RespQuit
    {
        public function __construct($exInfo=null, $rstCode=0)
        {
            $this->exInfo = is_null($exInfo) ? new CmdTxRxICE_RespPubInfo : $exInfo;
            $this->rstCode = $rstCode;
        }

        public function __toString()
        {
            global $CmdTxRxICE__t_RespQuit;
            return IcePHP_stringify($this, $CmdTxRxICE__t_RespQuit);
        }

        public $exInfo;
        public $rstCode;
    }

    $CmdTxRxICE__t_RespQuit = IcePHP_defineStruct('::CmdTxRxICE::RespQuit', 'CmdTxRxICE_RespQuit', array(
        array('exInfo', $CmdTxRxICE__t_RespPubInfo), 
        array('rstCode', $IcePHP__t_int)));
}
?>
